name = "acc-mcp-server"
main = "src/index.ts"
compatibility_date = "2025-06-20"
compatibility_flags = ["nodejs_compat"]

# Environment variables
[vars]
BASE_URL = "https://iot-api.acceleronix.io"
# ACCESS_KEY and ACCESS_SECRET should be configured as secrets via:
# npx wrangler secret put ACCESS_KEY
# npx wrangler secret put ACCESS_SECRET

# Durable Objects
[[durable_objects.bindings]]
name = "MCP_OBJECT"
class_name = "VirtualDataMCP"

# Observability
[observability]
enabled = true

# Migrations
[[migrations]]
tag = "v1"
new_sqlite_classes = ["VirtualDataMCP"]

[[migrations]]
tag = "v2"
deleted_classes = ["IoTMCP"]

[[migrations]]
tag = "v3"
new_sqlite_classes = ["VirtualDataMCP"]